---
title: "CANSSI Challenge"
author: "Titus"
date: '2019-09-14'
output: html_document
---

```{r}
library(mice)
library(dplyr)
library(pscl)
library(caret)
#original data
test = read.csv("test.csv")
vancouver = read.csv("vancouver.csv")
train = read.csv("train.csv")
traffic = read.csv("traffic.csv")
victoria = read.csv("victoria.csv")
#modified data
# train.merge2 = read.csv("train_mod2.csv")
# train.merge2 = dplyr::select(train.merge2,-X)
# testset = read.csv("Testset_mod1.csv")
# testset = dplyr::select(testset,-X)
# 
# # cleaning up the training set
# train.merge2$Van_Relative_Humidity_Per = factor(train.merge2$Van_Relative_Humidity_Per)
# train.merge2$Hour = factor(train.merge2$Hour)
# train.merge2$Vic_Relative_Humidity_Per = factor(train.merge2$Vic_Relative_Humidity_Per)
# train.merge2$Vic_Wind_Direct_Deg = factor(train.merge2$Vic_Wind_Direct_Deg)
# 
# # cleaning up the testing set
# testset$Vic_Wind_Direct_Deg = factor(testset$Vic_Wind_Direct_Deg)
# testset$Hour = factor(testset$Hour)
# testset$Van_Relative_Humidity_Per = factor(testset$Van_Relative_Humidity_Per)
# testset$Vic_Relative_Humidity_Per = factor(testset$Vic_Relative_Humidity_Per)

# combining the factor level of both training and testing data set
# col1 = levels(testset$Scheduled_Departure)
# col2 = levels(train.merge2$Scheduled_Departure)
# timelevel <- unique(c(col1, col2))
# train.merge2$Scheduled_Departure = factor(testset$Scheduled_Departure,levels = timelevel)
# testset$Scheduled_Departure = factor(testset$Scheduled_Departure,levels = timelevel)
# 
# col1 = levels(train.merge2$Van_Relative_Humidity_Per)
# col2 = levels(testset$Van_Relative_Humidity_Per)
# timelevel <- unique(c(col1, col2))
# train.merge2$Van_Relative_Humidity_Per = factor(testset$Van_Relative_Humidity_Per,levels = timelevel)
# testset$Van_Relative_Humidity_Per = factor(testset$Van_Relative_Humidity_Per,levels = timelevel)
# 
# col1 = levels(train.merge2$Hour)
# col2 = levels(testset$Hour)
# timelevel <- unique(c(col1, col2))
# train.merge2$Hour = factor(testset$Hour,levels = timelevel)
# testset$Hour = factor(testset$Hour,levels = timelevel)
# 
# col1 = levels(train.merge2$Vic_Relative_Humidity_Per)
# col2 = levels(testset$Vic_Relative_Humidity_Per)
# timelevel <- unique(c(col1, col2))
# train.merge2$Vic_Relative_Humidity_Per = factor(testset$Vic_Relative_Humidity_Per,levels = timelevel)
# testset$Vic_Relative_Humidity_Per = factor(testset$Vic_Relative_Humidity_Per,levels = timelevel)
# 
# col1 = levels(train.merge2$Vic_Wind_Direct_Deg)
# col2 = levels(testset$Hour)
# timelevel <- unique(c(col1, col2))
# train.merge2$Vic_Wind_Direct_Deg = factor(testset$Hour,levels = timelevel)
# testset$Vic_Wind_Direct_Deg = factor(testset$Vic_Wind_Direct_Deg,levels = timelevel)
```

```{r}
#Format the time date to join in to the training set, timezone GMT is used to avoid converstion error in PDT
#The time in the training set is round to hourly to better match the time in the weather data set
vancouver$formatedTimeDate = as.POSIXct(strptime(vancouver$Date.Time, "%Y-%m-%d %H:%M:%S"),tz = "GMT")
victoria$formatedTimeDate = as.POSIXct(strptime(victoria$Date.Time, "%Y-%m-%d %H:%M:%S"),tz = "GMT")
correctTime = format(strptime(train$Scheduled.Departure, "%I:%M %p"), format="%H:00:00")
correctDate = paste(train$Year,"-",match(train$Month,month.name),"-",train$Day.of.Month,sep = "")
correctTimeDate = paste(correctDate,correctTime)
train$formatedTimeDate = as.POSIXct(strptime(correctTimeDate,"%Y-%m-%d %H:%M:%S"),tz = "GMT")
VanWeather = vancouver[vancouver$formatedTimeDate >= "2016-08-28 05:15:00" &
                            vancouver$formatedTimeDate <= "2017-11-27 22:45:00",]
VictWeather = victoria[victoria$formatedTimeDate >= "2016-08-28 05:15:00" &
                            victoria$formatedTimeDate <= "2017-11-27 22:45:00",]

train.merged = left_join(train,VanWeather,by = "formatedTimeDate")
train.merged = left_join(train.merged,VictWeather,by = "formatedTimeDate")
```

```{r}
#Joining the data using left join and droping redudants columns
train.merged = select(train.merged,-c(Date.Time.x,Date.Time.y,Year.y,Month.y,Day.y,Time.x,Weather,
                         Full.Date,Year.x,Hour.x,Humidex.in.Celsius,Time.y,Year,Month,Day,Hour.y))


tempData = mice(select(train.merged,
                       Temperature.in.Celsius.x,
                       Dew.Point.Temperature.in.Celsius.x,
                       Relative.Humidity.in.Percent.x,
                       Temperature.in.Celsius.y,
                       Dew.Point.Temperature.in.Celsius.y,
                       Relative.Humidity.in.Percent.y,
                       Wind.Direction.in.Degrees,
                       Wind.Speed.km.per.h,
                       Visibility.in.km,
                       Station.Pressure.in.kPa),
                m=5,maxit = 5,method = "pmm",seed = 500)
completeData = complete(tempData,1)
#Drop old data that was use to impute

train.merged = select(train.merged,
                      -c(Temperature.in.Celsius.x,
                       Dew.Point.Temperature.in.Celsius.x,
                       Relative.Humidity.in.Percent.x,
                       Temperature.in.Celsius.y,
                       Dew.Point.Temperature.in.Celsius.y,
                       Relative.Humidity.in.Percent.y,
                       Wind.Direction.in.Degrees,
                       Wind.Speed.km.per.h,
                       Visibility.in.km,
                       Station.Pressure.in.kPa,
                       Trip.Duration))
names(completeData) = c("VanTemp_C","Van.DewPointTemp_C",
                        "VanRelativeHumid_Percent","VictTemp_C",
                        "VictDewPointTemp_C","VictRelativeHumid_Percent",
                        "VictWindDirection_Deg","VictWindSpeed_kmh",
                        "VictVisibility_km","VictStaionPressure_kPa")
names(train.merged)[5:6] = c("Day","Month")
train.merged = cbind(train.merged,completeData)
# only run to save the data
# write.csv(train.merged,"train_mod1.csv")
```


```{r}
correctTime = format(strptime(test$Scheduled.Departure, "%I:%M %p"), format="%H:00:00")
correctDate = paste(test$Year,"-",match(test$Month,month.name),"-",test$Day.of.Month,sep = "")
correctTimeDate = paste(correctDate,correctTime)
test$formatedTimeDate = as.POSIXct(strptime(correctTimeDate,"%Y-%m-%d %H:%M:%S"),tz = "GMT")
VanWeather2 = vancouver[vancouver$formatedTimeDate >= "2017-11-27 05:00:00" &
                            vancouver$formatedTimeDate <= "2018-03-30 22:00:00",]
VictWeather2 = victoria[victoria$formatedTimeDate >= "2017-11-27 05:00:00" &
                            victoria$formatedTimeDate <= "2018-03-30 22:00:00",]


test.merged = left_join(test,VanWeather2,by = "formatedTimeDate")
test.merged = left_join(test.merged,VictWeather2,by = "formatedTimeDate")
test.merged = select(test.merged,
                      -c(Date.Time.x,Date.Time.y,Year.y,Month.y,Day.y,Time.x,Weather,
                         Full.Date,Year.x,Hour.x,Humidex.in.Celsius,Time.y,Year,Month,Day,Hour.y))

tempData2 = mice(select(test.merged,
                       Temperature.in.Celsius.x,
                       Dew.Point.Temperature.in.Celsius.x,
                       Relative.Humidity.in.Percent.x,
                       Temperature.in.Celsius.y,
                       Dew.Point.Temperature.in.Celsius.y,
                       Relative.Humidity.in.Percent.y,
                       Wind.Direction.in.Degrees,
                       Wind.Speed.km.per.h,
                       Visibility.in.km,
                       Station.Pressure.in.kPa),
                m=5,maxit = 5,method = "pmm",seed = 500)
completeData2 = complete(tempData2,1)

test.merged = select(test.merged,
                      -c(Temperature.in.Celsius.x,
                       Dew.Point.Temperature.in.Celsius.x,
                       Relative.Humidity.in.Percent.x,
                       Temperature.in.Celsius.y,
                       Dew.Point.Temperature.in.Celsius.y,
                       Relative.Humidity.in.Percent.y,
                       Wind.Direction.in.Degrees,
                       Wind.Speed.km.per.h,
                       Visibility.in.km,
                       Station.Pressure.in.kPa))
names(completeData2) = c("VanTemp_C","Van.DewPointTemp_C",
                        "VanRelativeHumid_Percent","VictTemp_C",
                        "VictDewPointTemp_C","VictRelativeHumid_Percent",
                        "VictWindDirection_Deg","VictWindSpeed_kmh",
                        "VictVisibility_km","VictStaionPressure_kPa")
names(test.merged)[5:6] = c("Day","Month")
test.merged = cbind(test.merged,completeData2)

col1 = levels(test.merged$Scheduled.Departure)
col2 = levels(train.merged$Scheduled.Departure)
timelevel <- unique(c(col1, col2))
train.merged$Scheduled.Departure = factor(test.merged$Scheduled.Departure,levels = timelevel)
test.merged$Scheduled.Departure = factor(test.merged$Scheduled.Departure,levels = timelevel)
```


```{r}

trainset = createDataPartition(train.merge2$Delay_Indicator, p = .6, list = FALSE)
training = train.merge2[trainset,]
testing = train.merge2[-trainset,]

ctrl = trainControl(method = "repeatedcv", number = 10, savePredictions = TRUE)
mod_fit = train(Delay_Indicator ~
                  Vessel_Name +
                  Departure +
                  Arrival +
                  Traffic +
                  Scheduled_Departure +
                  Van_Temp_Cel +
                  Van_Relative_Humidity_Per +
                  Vic_Temp_Cel +
                  Vic_Dew_Point_Temp_Cel +
                  Vic_Wind_Speed +
                  Vic_Relative_Humidity_Per +
                  Vic_Visibility +
                  Vic_Station_Pressure +
                  Vic_Wind_Direct_Deg +
                  Day + Month + Hour +
                  Day_of_Month +
                  Day:Traffic +
                  Hour:Traffic +
                  Departure:Traffic,
                data = train.merge2,
                method="glm",
                family="binomial",
                trControl = ctrl,
                tuneLength = 5)

pred = data.frame(predict(mod_fit, newdata = testing))

pred$Delay_Indicator = ifelse(pred$predict.mod_fit..newdata...testing. >= 0.5,1,0)
pred$Delay_Indicator = factor(pred$Delay_Indicator)

testing$Delay_Indicator = factor(testing$Delay_Indicator)
pred = select(pred,-predict.mod_fit..newdata...testing.)

confusionMatrix(data = pred$Delay_Indicator, testing$Delay_Indicator)


```

```{r}
final_result = data.frame(predict(mod_fit,testset))
names(final_result) = "Delay.Indicator"
final_result$Delay.Indicator = ifelse(final_result$Delay.Indicator >= 0.5,1,0)
final_result$Delay.Indicator = factor(final_result$Delay.Indicator)
final_result = cbind(final_result,test$ID)
names(final_result) = c("Delay.Indicator","ID")
final_result = final_result[c("ID","Delay.Indicator")]
write.csv(temp,"submission.csv",row.names = F)

#dim(read.csv("submission.csv"))
#summary(read.csv("submission.csv"))
```

